### ISSUE TITLE
Support the wingpanel indicator API

### ISSUE THREAD

**Issue by quequotion** [alexmurray/indicator-sensors#23]
I know it's asking a lot for you to go out of your way to create an indicator for a niche DE like Pantheon, but there's currently no alternative for putting a sensor readout in the notification area.

elementary OS has dropped support of Ayatana indicators following GNOME's lead in enforcing Human Interface Guidelines that call for an end to application indicators--the notification area will only be used for system indicators in a future version of GNOME Shell as well (which is to be Ubuntu's default desktop following the death of Unity).

I think a sensor readout qualifies.

There is a [sample indicator](https://github.com/elementary/wingpanel/blob/master/sample/SampleIndicator.vala) written in Vala (the primary language used in elementary OS development); however, I think the indicator could just as well be written in C.

**Comment by alexmurray** [comment]
Looking at the sample this seems to be a loadable module which is loaded by wingpanel itself - so perhaps the way to do this would be to write a wingpanel indicator module that acts as a client to the DBus interface of indicator-sensors. This would be a separate project I think - see the existing gnome-shell extension which also works in a similar manner - https://github.com/alexmurray/gs-indicator-sensors-extension

Am closing this for now since unless I am not understanding wingpanel correctly, I think this should be a separate project.

**Comment by quequotion** [comment]
That certainly sounds possible!
